[package]
name = "kofl"
version = "0.1.0"
edition = "2021"
description = "A secure password manager CLI written in Rust"
[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"